version: '2.1'

services:
  ################################
  #   Setup Mysql container
  ################################
  docker-mysql:
    image: mysql:5.7
    container_name: docker-mysql
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      timeout: 30s
      retries: 10
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mutant

################################
#   Setup spring container
################################
  spring-boot:
    build: 
     context: ./mutant-api/
    image: mutant
    container_name: spring-boot
    depends_on:
       docker-mysql:
         condition: service_healthy
    ports:
      - 8090:8090

  frontend:
    build:
      context: ./mutant-client/
    ports:
      - 3000:3000
    depends_on:
      - spring-boot
